apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote
  name: vote
spec:
  replicas: 4
  selector:
    matchLabels:
      role: vote
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python
        role: vote
        version: v1
    spec:
      containers:
      - image: schoolofdevops/vote:v1
        name: vote
        ports:
        - containerPort: 80

